server:
  port: 8001
#mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.spike.springcloud.api.entity
#spring
spring:
  application:
    name: springcloud-provider-dept-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_demo_001?useUnicode=true&characterEncoding=utf-8
    password: springcloud
    username: spring_cloud_demo
# eureka的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: spring-cloud-provider-dept-8001 #修改eureka监控页面上的默认描述信息
# actuator的作用: 配置相关info信息
info:
  app.name: SpringCloud_Demo
  company.name: Spike.com